### ISSUE TITLE
No support for GCM and chacha20-poly ciphers

### ISSUE THREAD

**Issue by wiktor-k** [open-keychain/termbot#1]
Hello,
I'm trying to use termbot (1.9.2) but unfortunately it fails.

Relevant log message (taken with `adb -d logcat -v time -s TB.SSH`):
```
05-09 13:52:32.605 E/TB.SSH  (31554): Problem in SSH connection thread during authentication
05-09 13:52:32.605 E/TB.SSH  (31554): java.io.IOException: There was a problem while connecting to [redacted]:22
05-09 13:52:32.605 E/TB.SSH  (31554):   at com.trilead.ssh2.Connection.connect(Connection.java:808)
05-09 13:52:32.605 E/TB.SSH  (31554):   at com.trilead.ssh2.Connection.connect(Connection.java:590)
05-09 13:52:32.605 E/TB.SSH  (31554):   at org.connectbot.transport.SSH.connect(SSH.java:495)
05-09 13:52:32.605 E/TB.SSH  (31554):   at org.connectbot.service.TerminalBridge$3.run(TerminalBridge.java:286)
05-09 13:52:32.605 E/TB.SSH  (31554):   at java.lang.Thread.run(Thread.java:764)
05-09 13:52:32.605 E/TB.SSH  (31554): Caused by: java.io.IOException: Key exchange was not finished, connection is closed.
05-09 13:52:32.605 E/TB.SSH  (31554):   at com.trilead.ssh2.transport.KexManager.getOrWaitForConnectionInfo(KexManager.java:149)
05-09 13:52:32.605 E/TB.SSH  (31554):   at com.trilead.ssh2.transport.TransportManager.getConnectionInfo(TransportManager.java:157)
05-09 13:52:32.605 E/TB.SSH  (31554):   at com.trilead.ssh2.Connection.connect(Connection.java:760)
05-09 13:52:32.605 E/TB.SSH  (31554):   ... 4 more
05-09 13:52:32.605 E/TB.SSH  (31554): Caused by: java.io.IOException: Cannot negotiate, proposals do not match.
05-09 13:52:32.605 E/TB.SSH  (31554):   at com.trilead.ssh2.transport.KexManager.handleMessage(KexManager.java:540)
05-09 13:52:32.605 E/TB.SSH  (31554):   at com.trilead.ssh2.transport.TransportManager.receiveLoop(TransportManager.java:617)
05-09 13:52:32.605 E/TB.SSH  (31554):   at com.trilead.ssh2.transport.TransportManager$1.run(TransportManager.java:311)
05-09 13:52:32.605 E/TB.SSH  (31554):   ... 1 more
```

My `/etc/ssh/sshd_config` includes these:

```
KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com
```

There is no `HostKeyAlgorithms` used, but there are two `HostKey` preferences (one RSA and one ed25519).

`/var/log/auth` contains a relevant line:
```
May  9 07:52:09 [redacted] sshd[11665]: fatal: no matching cipher found:
client aes128-ctr,aes192-ctr,aes256-ctr,aes256-cbc,rijndael-cbc@lysator.liu.se,aes192-cbc,aes128-cbc,blowfish-cbc,arcfour128,arcfour,cast128-cbc,3des-cbc
server chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com [preauth]
```

It seems GCM algorithms and chacha20 are not supported. Is modernization of client ciphers planned for TermBot?

**Comment by hagau** [comment]
Thanks for the report!

Hm, this is a sshlib issue rather than a TermBot one.
I'll leave this open for now, since I'm not certain how to procceed right now.

There is definitely interest to support more modern ciphers in sshlib, but there are no immediate plans to do so.

**Comment by wiktor-k** [comment]
Thanks @hagau!
It seems not many libraries support these parameters, but this list may be useful for someone: https://ssh-comparison.quendi.de/comparison/cipher.html

**Comment by dschuermann** [comment]
Closing. Issues for current release are tracked here: https://github.com/cotechde/termbot/issues
