### ISSUE TITLE
Crash when selecting 'Use external agent' on Xperia Z2, Android 6.0.1

### ISSUE THREAD

**Issue by wsot** [open-keychain/termbot#8]
Termbot version 1.9.2-termbot.2
OpenKeyChain version 5.0.2

Device:
Xperia Z2 (D6503)
Android 6.0.1, patch level 1 may 2016
Build number 23.5.A.1.291
(Not rooted, bootloader locked)

Steps to reproduce:
1. Open termbot
2. Click '+' to add host
3. Scroll down and click 'Use pubkey authentication'
4. Click 'user external agent'
Result: 'Unfortunately TermBot has stopped.'

```
05-26 14:22:36.116: D/AndroidRuntime(6238): Shutting down VM
05-26 14:22:36.116: E/AndroidRuntime(6238): FATAL EXCEPTION: main
05-26 14:22:36.116: E/AndroidRuntime(6238): Process: org.sufficientlysecure.termbot, PID: 6238
05-26 14:22:36.116: E/AndroidRuntime(6238): android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
05-26 14:22:36.116: E/AndroidRuntime(6238): 	at android.app.ContextImpl.startActivity(ContextImpl.java:658)
05-26 14:22:36.116: E/AndroidRuntime(6238): 	at android.app.ContextImpl.startActivity(ContextImpl.java:645)
05-26 14:22:36.116: E/AndroidRuntime(6238): 	at android.content.ContextWrapper.startActivity(ContextWrapper.java:331)
05-26 14:22:36.116: E/AndroidRuntime(6238): 	at org.connectbot.service.AgentManager.executePendingIntent(AgentManager.java:169)
05-26 14:22:36.116: E/AndroidRuntime(6238): 	at org.connectbot.service.AgentManager.processResponse(AgentManager.java:144)
05-26 14:22:36.116: E/AndroidRuntime(6238): 	at org.connectbot.service.AgentManager.access$100(AgentManager.java:38)
05-26 14:22:36.116: E/AndroidRuntime(6238): 	at org.connectbot.service.AgentManager$2.onReturn(AgentManager.java:122)
05-26 14:22:36.116: E/AndroidRuntime(6238): 	at org.openintents.ssh.authentication.SshAuthenticationApi$SshAgentAsyncTask.onPostExecute(SshAuthenticationApi.java:169)
05-26 14:22:36.116: E/AndroidRuntime(6238): 	at org.openintents.ssh.authentication.SshAuthenticationApi$SshAgentAsyncTask.onPostExecute(SshAuthenticationApi.java:154)
05-26 14:22:36.116: E/AndroidRuntime(6238): 	at android.os.AsyncTask.finish(AsyncTask.java:651)
05-26 14:22:36.116: E/AndroidRuntime(6238): 	at android.os.AsyncTask.access$500(AsyncTask.java:180)
05-26 14:22:36.116: E/AndroidRuntime(6238): 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
05-26 14:22:36.116: E/AndroidRuntime(6238): 	at android.os.Handler.dispatchMessage(Handler.java:102)
05-26 14:22:36.116: E/AndroidRuntime(6238): 	at android.os.Looper.loop(Looper.java:234)
05-26 14:22:36.116: E/AndroidRuntime(6238): 	at android.app.ActivityThread.main(ActivityThread.java:5526)
05-26 14:22:36.116: E/AndroidRuntime(6238): 	at java.lang.reflect.Method.invoke(Native Method)
05-26 14:22:36.116: E/AndroidRuntime(6238): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
05-26 14:22:36.116: E/AndroidRuntime(6238): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

Other possibly relevant information:

- There is one key in OpenKeychain, which is stored on a Yubikey Neo
- There are no other hosts configured in TermBot
- This problem doesn't happen on the Pixel 2 with Android 8.1, nor the Galaxy S7 (exynos variant) with Android 7.something.

Update:
Also occurs on Nexus 10 running Android 5.1.1
Also occurs on Teclast 98 running Android 6.0

**Comment by hagau** [comment]
Thanks for the report!

This should be fixed with https://github.com/open-keychain/termbot/commit/bb9cad9330fc11ae900dbc3b483b13e84fafc4a8 which will be released in 1.9.2-termbot.3 soon.
